export default defineAppConfig({
  pages: [
    'pages/journey/index',
    'pages/journey/milestones/index',
    'pages/journey/list/index',
    'pages/journey/calendar/index',
    'pages/journey/vaccine/index',
    'pages/journey/weekly-insight/index',
    'pages/baby-profile/index',
    'pages/baby-profile/photo/index',
    'pages/wishes/index',
    'pages/wishes/detail/index',
    'pages/wishes/counter/index',
    'pages/family/index',
    'pages/family/invite/index',
    'pages/family/invite/token/index',
    'pages/family/invited/index',
    'pages/family/memories/index',
    'pages/family/poster/index',
    'pages/analysis/growth/index',
    'pages/analysis/sleep-daily/index',
    'pages/analysis/sleep-monthly/index',
    'pages/analysis/diet-week/index',
    'pages/analysis/diet-month/index',
    'pages/analysis/mood/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'Nurture & Bloom',
    navigationBarTextStyle: 'black',
    backgroundColor: '#fbf9f6',
  },
})
