/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#c1edd1',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#a6d0b6',
        'tertiary-container': '#f7fff7',
        'primary-container': '#fffdf5',
        surface: '#fff8f1',
        secondary: '#765842',
        'on-primary': '#ffffff',
        'inverse-surface': '#33302b',
        'secondary-fixed-dim': '#e6bfa4',
        'primary-fixed-dim': '#c8c7bf',
        'on-secondary-container': '#795b44',
        'secondary-fixed': '#ffdcc4',
        'inverse-on-surface': '#f7f0e8',
        'surface-bright': '#fff8f1',
        outline: '#777770',
        'surface-container-highest': '#e8e1d9',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#474741',
        'on-primary-fixed-variant': '#474742',
        'outline-variant': '#c8c7be',
        primary: '#5f5f59',
        'primary-fixed': '#e4e3db',
        'on-surface': '#1e1b17',
        'on-primary-fixed': '#1b1c17',
        'on-secondary-fixed-variant': '#5c412c',
        'surface-dim': '#e0d9d1',
        'on-secondary-fixed': '#2b1706',
        'surface-container': '#f4ede5',
        'on-background': '#1e1b17',
        'on-tertiary-container': '#557d66',
        'on-tertiary-fixed-variant': '#284e3a',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#002112',
        'on-tertiary': '#ffffff',
        tertiary: '#406651',
        'surface-variant': '#e8e1d9',
        'on-error': '#ffffff',
        'inverse-primary': '#c8c7bf',
        'surface-container-low': '#faf2ea',
        'on-primary-container': '#75756e',
        'surface-tint': '#5f5f59',
        'surface-container-lowest': '#ffffff',
        background: '#fff8f1',
        'secondary-container': '#fed5b9',
        'surface-container-high': '#eee7df',
        // 心愿清单各卡片的图标圆底配色。五种心愿各有识别色，
        // 按 analysis.* 的先例收成一组命名空间，页面里不写死色值。
        wish: {
          swim: '#9DB4BC',
          museum: '#D08F6A',
          trails: '#CFE0BC',
          books: '#8AA0A8',
          climbing: '#D9925C',
          // 勾选项的圆底：比 swim 更深的青灰，承载白色对勾
          active: '#4E6A72',
        },
        // 家庭成员头像配色。三个成员各用一种醒目色，既推不出现有语义色，
        // 又会在首页 / 成员管理 / 邀请流程里重复出现，按 analysis / wish 的先例
        // 收成命名空间，页面里不写死色值。
        family: {
          clay: '#c98d6b',
          sage: '#a8bfa8',
          lilac: '#c9b6e4',
          // 长图海报的底色，是这一模块独有的品牌绿
          poster: '#c9d4bd',
        },
        analysis: {
          'text-primary': '#2E2822',
          'text-secondary': '#6F6760',
          'text-tertiary': '#8C857D',
          'text-muted': '#9B958E',
          'title-accent': '#835332',
          'highlight': '#D57C69',
          'active-bg': '#D9E7CE',
          'active-text': '#5B7358',
          'inactive-bg': '#EFEEEB',
          'inactive-text': '#7A766F',
          'card-border': '#E4DFD9',
          'card-muted-border': '#E0DAD2',
          'card-muted-bg': '#F4F1EC',
          'chart-surface': '#F7F4EF',
          'chart-border': '#E6DDD4',
          'chart-bg': '#F2EEEA',
          'chart-border-light': '#DDD7CF',
          'chart-grid-border': '#ECE4DB',
          'highlight-orange': '#C97D55',
          'highlight-olive': '#88A48A',
          'sleep-night': '#97A8AF',
          'sleep-nap': '#D2C9BC',
          'sleep-awake': '#E7E8E6',
          'icon-bg': '#ECE8E2',
          'metric-label': '#92613A',
          'metric-value': '#8B5A2B',
          'metric-unit': '#8B8A86',
          'ingredient-border': '#CFC8BF',
          'more-bg': '#EBE7E2',
          'more-border': '#BFB7AE',
          'more-text': '#6D6761',
          'progress-label': '#585A55',
          'progress-count': '#6B775F',
          'unlocked-bg': '#D2DFC4',
          'unlocked': '#5C6D56',
          'locked': '#8C8D88',
          'locked-text': '#5F6857',
          'locked-label': '#7A7671',
          'divider': '#ECE6DF',
          'trash': '#86807A',
          'dashed-border': '#D8DDD8',
          'ring-icon': '#7E959F',
          'ring-text': '#64757C',
          'draft-close': '#9B8F86',
          'inactive-border': '#9AB5BE',
          'sync-inactive': '#CAD6DA',
          'segment-night': '#485F65',
          'segment-nap': '#8EA584',
          'segment-awake': '#E5DFD8',
          'segment-awake-border': '#D8D2CB',
          'legend-text': '#4A423B',
          'sub-text': '#A8A09A',
          'evolution-bg': '#ECE6DF',
          'muted-label': '#5F5A53',
          'muted-text': '#8E867D',
          'footer-bg': '#F3F5EE',
          'footer-text': '#8C827A',
          'badge': '#6D6A64',
          'success-bg': '#6E8F7A',
          'input-bg': '#F5F2EE',
          'narrative-icon': '#5C6D76',
          'mood-happy-bg': '#EDF3E3',
          'mood-happy-text': '#66755E',
          'mood-happy-dot': '#D1DBC2',
          'mood-happy-border': '#D7DFCF',
          'mood-clingy-bg': '#F3DFD8',
          'mood-clingy-text': '#8F5A36',
          'mood-clingy-dot': '#D8A08A',
          'mood-clingy-border': '#E5C0B5',
          'mood-discomfort-bg': '#EDF0F1',
          'mood-discomfort-text': '#677780',
          'mood-discomfort-dot': '#97A8AF',
          'mood-discomfort-border': '#D7DEE1',
          'mood-empty-bg': '#F0EEEB',
          'mood-empty-text': '#C4BDB4',
          'mood-divider': '#E5DFD8',
          'mood-day-disabled': '#CBC3BA',
          'mood-icon': '#6A7A81',
          'mood-tag-bg': '#F1D7CF',
          'mood-tag-text': '#8F5A36',
          'mood-accent': '#D29078',
          'mood-checkin-icon': '#7B95A0',
          'mood-checkin-border': '#D8E2DB',
          'mood-inactive-border': '#EBE7E1',
        },
      },
      fontFamily: {
        'plus-jakarta': ['Plus Jakarta Sans', 'sans-serif'],
        'nunito-sans': ['Nunito Sans', 'sans-serif'],
        icons: ['Material Symbols Outlined', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        '4xl': '1.75rem',
        '5xl': '2rem',
        full: '9999px',
      },
      spacing: {
        // 用 rem 而不是 px。Taro 的 pxtransform 会把 px 按 deviceRatio 换算成 rpx，
        // 而本项目 designWidth 390 对应的 deviceRatio 是 1，写 px 会得到设计尺寸的一半
        // （20px → 20rpx，在 390 宽机型上只有 10.4px）。
        // Tailwind 自身的间距体系本来就基于 rem，这里对齐它，token 才能和内置类同尺度。
        'margin-mobile': '1.25rem',
        'gutter-mobile': '0.75rem',
        xl: '2rem',
        lg: '1.5rem',
        xs: '0.5rem',
        sm: '0.75rem',
        md: '1rem',
        base: '0.25rem',
      },
      fontSize: {
        // 同上，一律用 rem 表述设计尺寸（按 16px 基准换算），避免被转成 rpx 后减半。
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        caption: ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
        'headline-lg': ['1.75rem', { lineHeight: '2.25rem', fontWeight: '600' }],
        'body-md': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.625rem', fontWeight: '400' }],
        'headline-lg-mobile': ['1.5rem', { lineHeight: '2rem', fontWeight: '600' }],
        display: ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
      },
      boxShadow: {
        card: '0 10px 30px rgba(31, 42, 46, 0.08)',
        float: '0 16px 32px rgba(73, 98, 105, 0.24)',
        modal: '0 24px 60px rgba(31, 42, 46, 0.16)',
        // 暖调卡片阴影（里程碑 / 心愿 / 家庭分享的信息卡）。
        // 设计稿里同一批卡片给了 0,8/32 与 0,4/24 两种近似的暖色阴影，
        // 属于未精修导致的不一致，这里归一为一种，避免同一列表里卡片层次跳变。
        'card-soft': '0 0.5rem 2rem rgba(118, 88, 66, 0.06)',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
}
