#!/usr/bin/env bash
# Run the whole guideline RAG pipeline end to end, then verify the result.
#
#   PDF -> data/_work/extract/*.jsonl      (pdf_extract.py, or ocr_pages.py)
#       -> data/guidelines/**/*.md         (build_guidelines.py)
#       -> knowledge_documents/chunks      (app.knowledge.ingest_guidelines)
#       -> pass/fail report                (verify_guidelines.py)
#
# Every stage is idempotent, so re-running this after adding a PDF or editing a
# profile only rewrites what changed. The script exits non-zero if any stage
# fails, so it is safe to wire into CI.
#
# Sources come in two tiers, and stage 1 picks the tool per tier:
#   SOURCES          text-layer PDFs, extracted by pdf_extract.py (seconds a book)
#   SCANNED_SOURCES  image-only PDFs, OCR'd by ocr_pages.py (minutes a book)
# Both write the same JSONL contract, so stages 2-4 cannot tell them apart.
#
# Usage
#   scripts/run_guidelines_pipeline.sh            # full run
#   scripts/run_guidelines_pipeline.sh --no-ocr   # skip the scanned tier
#   scripts/run_guidelines_pipeline.sh --verify   # verify an existing ingest
#   scripts/run_guidelines_pipeline.sh --no-verify
#
# Lifespan:
#   Stable tooling. Add one entry to SOURCES or SCANNED_SOURCES per new PDF.

set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

PY="${PY:-.venv/bin/python}"

# The OCR engine is macOS Vision, reached through `ocrmac`, which needs its own
# interpreter: it is a system-framework binding, not something the app's venv
# should carry. OCR_SKIP is set when that interpreter is absent, so a machine
# without it still runs the text-layer tier.
PY_OCR="${PY_OCR:-$HOME/.venvs/babygrow-ocr/bin/python}"

# slug : PDF filename inside <repo>/docs/rag_docs
SOURCES=(
  "postpartum_diet:014-2022+产褥期妇女膳食指导.pdf"
  "complementary_feeding:婴幼儿辅食添加营养指南.pdf"
  "cuiyutao_natural_parenting:崔玉涛自然养育法.pdf"
)

# Image-only PDFs, no text layer at all -- see docs/rag-ocr-b-tier.md.
# An optional third field limits the last page read. A scanned download can end
# with a page that is not book content at all (see the sync book below), and
# bounding the page range is more auditable than filtering the text later.
#
#   0-3岁宝宝喂养同步指导: the scan carries one extra page (314) generated by
#   the archive it came from -- provenance boilerplate and the source zip's
#   name, hashes and page count. No book text on it, so it is not read.
SCANNED_SOURCES=(
  "zhongguo_dietary_guidelines:中国居民膳食指南（2022）.pdf"
  "cuiyutao_parenting_encyclopedia:崔玉涛育儿百科 崔玉涛 Z-Library.pdf"
  "feeding_sync_guidance:0-3岁宝宝喂养同步指导.PDF:313"
)

RUN_PIPELINE=1
RUN_VERIFY=1
RUN_OCR=1
for arg in "$@"; do
  case "$arg" in
    --verify) RUN_PIPELINE=0 ;;
    --no-verify) RUN_VERIFY=0 ;;
    --no-ocr) RUN_OCR=0 ;;
    -h|--help) sed -n '2,25p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

if [[ ! -x "$PY" ]]; then
  echo "Python interpreter not found at $PY (set PY=/path/to/python)" >&2
  exit 1
fi

if [[ "$RUN_OCR" == 1 && ! -x "$PY_OCR" ]]; then
  echo "warning: OCR interpreter not found at $PY_OCR" >&2
  echo "         skipping the scanned tier; set PY_OCR=/path/to/python to run it" >&2
  RUN_OCR=0
fi

RAG_DOCS="$("$PY" -c 'import sys; sys.path.insert(0, "scripts"); from rag_paths import rag_docs_dir; print(rag_docs_dir())')"
WORK_DIR="$(dirname "$0")/../data/_work"

stage() { printf '\n=== %s ===\n' "$*"; }

# Split a "<slug>:<filename>[:<last_page>]" entry into SLUG, PDF_NAME, LAST_PAGE.
parse_entry() {
  SLUG="${1%%:*}"
  local rest="${1#*:}"
  if [[ "$rest" == *:* ]]; then
    PDF_NAME="${rest%%:*}"
    LAST_PAGE="${rest##*:}"
  else
    PDF_NAME="$rest"
    LAST_PAGE=""
  fi
}

if [[ "$RUN_PIPELINE" == 1 ]]; then
  # Preflight: fail before touching the database if a source PDF is missing.
  missing=0
  for entry in "${SOURCES[@]}"; do
    pdf="$RAG_DOCS/${entry#*:}"
    if [[ ! -f "$pdf" ]]; then
      echo "missing source PDF: $pdf" >&2
      missing=1
    fi
  done
  if [[ "$RUN_OCR" == 1 ]]; then
    for entry in "${SCANNED_SOURCES[@]}"; do
      parse_entry "$entry"
      pdf="$RAG_DOCS/$PDF_NAME"
      if [[ ! -f "$pdf" ]]; then
        echo "missing scanned PDF: $pdf" >&2
        missing=1
      fi
    done
  fi
  [[ "$missing" == 0 ]] || { echo "Aborting: source PDFs are incomplete." >&2; exit 1; }

  stage "1/4 extract PDFs -> JSONL"
  for entry in "${SOURCES[@]}"; do
    slug="${entry%%:*}"
    pdf="$RAG_DOCS/${entry#*:}"
    echo "--- $slug"
    "$PY" scripts/pdf_extract.py \
      --pdf "$pdf" \
      --out "$WORK_DIR/extract/$slug.jsonl" \
      > "$WORK_DIR/extract/$slug.report.json"
    "$PY" -c 'import json,sys; r=json.load(open(sys.argv[1])); print(json.dumps(r, ensure_ascii=False))' \
      "$WORK_DIR/extract/$slug.report.json"
  done

  # The scanned tier is minutes rather than seconds a book, and both tiers write
  # the same JSONL, so the rest of the pipeline is unaware of the difference.
  if [[ "$RUN_OCR" == 1 ]]; then
    for entry in "${SCANNED_SOURCES[@]}"; do
      parse_entry "$entry"
      pdf="$RAG_DOCS/$PDF_NAME"
      echo "--- $SLUG (OCR${LAST_PAGE:+, last page $LAST_PAGE})"
      ocr_args=(--pdf "$pdf" --out "$WORK_DIR/extract/$SLUG.jsonl")
      [[ -n "$LAST_PAGE" ]] && ocr_args+=(--last "$LAST_PAGE")
      "$PY_OCR" scripts/ocr_pages.py "${ocr_args[@]}" \
        > "$WORK_DIR/extract/$SLUG.report.json"
      cat "$WORK_DIR/extract/$SLUG.report.json"
    done
  fi

  stage "2/4 build structured Markdown"
  "$PY" scripts/build_guidelines.py

  stage "3/4 ingest into the knowledge base"
  "$PY" -m app.knowledge.ingest_guidelines
else
  stage "skipping pipeline (--verify)"
fi

if [[ "$RUN_VERIFY" == 1 ]]; then
  stage "4/4 verify"
  "$PY" scripts/verify_guidelines.py
else
  stage "skipping verification (--no-verify)"
fi

printf '\nPipeline complete.\n'
